version: '3'
services:
  mysql-test:
    image: mysql:5.7
    restart: always
    container_name: mysql-test
    hostname: mysql-test
    environment:
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'root'
      TZ: Asia/Shanghai
    ports:
      - 3306:3306
    volumes:
      - ./conf/my.cnf:/etc/mysql/my.cnf
